const STORAGE_KEY='catchme_v02';
const CHAPTERS=[
{key:'catch',num:'01',title:'CATCH ME',subtitle:'How do you love?',desc:'先建立你的 baseline：心動、安全感、自由、界線。',color:'acid'},
{key:'flirt',num:'02',title:'FLIRT WITH ME',subtitle:'How do you play?',desc:'眼神、訊息、反殺、死機。這章開始比較不正經。',color:'lav'},
{key:'after',num:'03',title:'AFTER DARK',subtitle:'Desire & intimacy',desc:'親密、慾望、界線與被想要的方式。',locked:true},
{key:'trust',num:'04',title:'TRUST ISSUES',subtitle:'FBI ONLINE',desc:'吃醋、透明度、第三者與信任修復。',locked:true},
{key:'fight',num:'05',title:'FIGHT ME',subtitle:'Conflict & repair',desc:'吵架、暫停、道歉、三次法則。',locked:true},
{key:'life',num:'06',title:'BUILD A LIFE',subtitle:'The real final boss',desc:'工作、錢、遠距、家人與人生選擇。',locked:true}
];
const Q={
catch:[
{text:'聚會裡有個人一直偷偷看你。你發現了。',opts:['裝沒看到，繼續做自己的事','直接看回去。🙂','笑一下，再移開視線','等等，他為什麼一直看？開始觀察','都不是，我有自己的版本'],traits:{A:['freedom'],B:['spark','direct'],C:['spark','soft'],D:['depth','clarity'],E:['depth']}},
{text:'對方突然說：「你今天很好看。」',opts:['「謝謝。」然後迅速轉移話題','「真的嗎？哪裡？」','笑著回：「你今天也不錯啊。」','表面淡定，內心已經死機','我要自己回答'],traits:{A:['freedom'],B:['depth','direct'],C:['spark'],D:['soft','spark'],E:['depth']}},
{text:'你最容易被哪一種瞬間擊中？',opts:['平常很鬧，突然認真處理事情','平常很成熟，私下突然超可愛','一句很準的冷面吐槽','安靜的人突然講出很深的想法','沒有固定，我真的看人'],traits:{A:['competence','spark'],B:['soft','contrast'],C:['spark','contrast'],D:['depth','contrast'],E:['freedom']}},
{text:'你們聊天超合，但他偶爾會消失幾個小時。',opts:['正常啊，大家都有自己的生活','可以，但提前講一聲我會更舒服','完全沒差，我也常消失','開始想：是不是哪裡不對？','看情況，我自己說'],traits:{A:['freedom','trust'],B:['clarity','trust'],C:['freedom'],D:['clarity','depth'],E:['depth']}},
{text:'最理想的約會，比較像哪個？',opts:['一起亂逛，看到什麼就做什麼','有安排，但中間保留很多即興','漂亮餐廳，好好打扮一次','在家耍廢聊天到半夜','我的版本比較奇怪'],traits:{A:['freedom','spark'],B:['balance','spark'],C:['aesthetic','spark'],D:['depth','soft'],E:['freedom']}},
{text:'對方很香，而且靠得有點近。',opts:['救命，先不要說話','我會直接調情回去','表面沒事，腦袋已經不在線','退一點，我需要自己的距離','研究員管太多，我自己答'],traits:{A:['spark','soft'],B:['spark','direct'],C:['spark','contrast'],D:['freedom'],E:['spark']}},
{text:'你心情不好，但還沒準備好講。你希望他？',opts:['察覺到，問一次，然後把選擇權留給我','抱抱我，不急著問原因','想辦法把我逗笑','幫我分析到底發生什麼','都不完全是'],traits:{A:['trust','freedom'],B:['soft','trust'],C:['spark','soft'],D:['clarity','competence'],E:['depth']}},
{text:'你發現他跟某個人互動有點曖昧。第一步？',opts:['直接問清楚，不演內心劇場','先觀察一下再說','如果只是正常社交，我不管','開玩笑試探，看他反應','我的 FBI 有自己的 SOP'],traits:{A:['clarity','direct'],B:['depth','clarity'],C:['freedom','trust'],D:['spark','depth'],E:['clarity']}},
{text:'你們第一次真正吵架，他說：「我現在不想談。」',opts:['好，但我們約一個時間再談','不行，今天至少要講到一個段落','可以，等你準備好再找我','我也冷掉，先各自消失','我要開記者會，選項不夠'],traits:{A:['clarity','balance'],B:['direct','clarity'],C:['freedom','trust'],D:['freedom'],E:['direct']}},
{text:'同一個問題已經發生第三次。',opts:['再談一次，也許這次真的能解決','開始評估這是不是根本不適合','直接離開，我的額度用完了','看問題嚴重程度，不一刀切','我有自己的判準'],traits:{A:['soft'],B:['clarity','competence'],C:['boundary','direct'],D:['balance','depth'],E:['boundary']}},
{text:'你們對未來規劃完全不同，但都還很愛。',opts:['一起找中間方案，先別急著放棄','愛不夠，現實不合就該停','其中一個人可以多讓一點','先把各自不能退的底線講清楚','太複雜，我要自己答'],traits:{A:['balance','trust'],B:['boundary','clarity'],C:['soft'],D:['clarity','balance'],E:['depth']}},
{text:'你最想要的親密感是？',opts:['各忙各的，但知道對方一直在','什麼都能聊，腦袋完全對頻','很多肢體接觸和日常黏在一起','一起冒險、一起玩、一起長大','不能只選一個吧？'],traits:{A:['freedom','trust'],B:['depth','clarity'],C:['soft'],D:['spark','balance'],E:['balance']}},
{text:'哪句話最容易讓你真正安心？',opts:['「去做你的事，我在。」','「有問題我們一起處理。」','「我每天都想見你。」','「我選你，而且我會讓你知道。」','都不是，我自己寫'],traits:{A:['freedom','trust'],B:['competence','trust'],C:['soft'],D:['clarity','trust'],E:['trust']}},
{text:'一個人很有火花，但總讓你猜；另一個很穩，但完全沒火花。',opts:['選有火花的，至少我真的喜歡','選穩的，安全比較重要','兩個都不要','先看能不能把第一個的問題談清楚','這題太壞了，我拒答'],traits:{A:['spark'],B:['trust'],C:['boundary','balance'],D:['spark','clarity'],E:['freedom']}},
{text:'最後一題。你覺得愛最接近哪一句？',opts:['我不需要你完成我，但我希望你站在我旁邊','喜歡就是想一直靠近一個人','即使不同，我們還是一次次選擇彼此','有人真正看見我，而且沒有離開','我不想替愛下定義'],traits:{A:['freedom','balance'],B:['soft','spark'],C:['trust','balance'],D:['depth','trust'],E:['freedom','depth']}}
],
flirt:[
{text:'你發現喜歡的人一直看你。最像你的反應？',opts:['裝作不知道，想看他能撐多久','直接抓包：「你一直看我幹嘛？」','看回去，什麼都不說','先笑，然後自己害羞','別管我，我會自行犯罪'],traits:{A:['tension','contrast'],B:['direct','spark'],C:['tension','confidence'],D:['soft','spark'],E:['spark','confidence']}},
{text:'他被抓到後說：「因為你好看啊。」',opts:['「我知道。」😎','「真的嗎？哪裡？」','「你今天也不錯。」','笑到不知道回什麼','我要自己回'],traits:{A:['confidence'],B:['tension','depth'],C:['reciprocity','spark'],D:['soft'],E:['direct']}},
{text:'五分鐘後他突然問：「你剛剛是不是害羞了？」',opts:['否認到底','「有嗎？」🙂','「你很煩欸🤣」','反問：「所以你剛剛一直在看？」','我有更狠的'],traits:{A:['tension'],B:['tension','soft'],C:['play','spark'],D:['direct','play'],E:['confidence']}},
{text:'你已經確定彼此有意思。誰主動比較理想？',opts:['他多一點，我喜歡被明確想要','我多一點，我喜歡掌握節奏','輪流。誰想靠近誰就靠近','不用固定，看氣氛','角色固定很無聊，我自己說'],traits:{A:['reciprocity','soft'],B:['confidence','direct'],C:['reciprocity','balance'],D:['tension','freedom'],E:['freedom']}},
{text:'他平常很主動，某天突然停下來等你。',opts:['好，那換我。🙂','我會害羞到卡住','故意不動，看誰先輸','會覺得氣氛斷掉','我的反應不能公開'],traits:{A:['confidence','reciprocity'],B:['soft','tension'],C:['tension','play'],D:['clarity'],E:['spark']}},
{text:'如果永遠都只有你主動？',opts:['沒差，我喜歡主導','久了會下頭，我也想感覺被想要','我會直接問他是不是沒興趣','我會默默減少主動','看情況，我不一刀切'],traits:{A:['confidence'],B:['reciprocity','spark'],C:['clarity','direct'],D:['boundary'],E:['balance']}},
{text:'哪一個最容易讓你突然心跳漏拍？',opts:['「你今天很好看。」','「我想你。」','「過來。」','他記得一個超小的細節','很難說，我的弱點很怪'],traits:{A:['aesthetic'],B:['soft','reciprocity'],C:['confidence','spark'],D:['attention','depth'],E:['contrast']}},
{text:'「過來。」然後真的只是把你抱住。',opts:['救命，這個很可以','太直接，我會退一步','我會抱回去，順便笑他','表面冷靜，內部爆炸','研究員不要問了'],traits:{A:['soft','spark'],B:['freedom'],C:['reciprocity','play'],D:['tension','spark'],E:['spark']}},
{text:'公開場合他很正常，私下突然親密很多。',opts:['我超吃，只有我知道這個版本','我比較喜歡公開也自然一點','都可以，不要刻意就好','會讓我懷疑他是不是在藏關係','看關係階段'],traits:{A:['exclusivity','contrast'],B:['clarity'],C:['balance'],D:['clarity','trust'],E:['depth']}},
{text:'哪種瞬間比較容易讓你覺得「靠，這人好性感」？',opts:['認真工作、能力全開','穿得超好看','笑得很好看','反殺我一句，讓我當場死機','如果又很好聞，以上全部加倍'],traits:{A:['competence','spark'],B:['aesthetic'],C:['soft'],D:['play','confidence'],E:['sensory','spark']}},
{text:'一個人很會撩，但你發現他對很多人都這樣。',opts:['還是很有魅力啊','直接打折，我要的是對我不一樣','反而覺得有挑戰性','會吃醋但不至於下頭','看他有沒有真正的界線'],traits:{A:['spark'],B:['exclusivity','trust'],C:['confidence'],D:['reciprocity'],E:['boundary','trust']}},
{text:'你丟了一個很明顯的球，他居然沒接到。',opts:['再丟一次，菜就多練','直接笑爛，算了','我會懷疑他是不是沒興趣','過幾天換一種方式','我會當場問：「你沒發現？」'],traits:{A:['play','confidence'],B:['play'],C:['clarity'],D:['balance'],E:['direct','clarity']}},
{text:'哪種聊天最容易越聊越暈？',opts:['一直互嘴，偶爾突然很真心','每天穩穩聊生活小事','深夜聊價值觀、人生與秘密','曖昧拉扯，不把話講完','全部要看人'],traits:{A:['play','contrast'],B:['trust','soft'],C:['depth','attention'],D:['tension','spark'],E:['balance']}},
{text:'你比較容易被哪種「偏愛」擊中？',opts:['在人群裡第一個找我','只記得我講過的小事','私下對我特別幼稚／柔軟','直接說：「我就是喜歡你。」','拜託不要逼我選'],traits:{A:['attention','exclusivity'],B:['attention','depth'],C:['contrast','exclusivity'],D:['clarity','reciprocity'],E:['balance']}},
{text:'FLIRT FINAL。你真正喜歡的調情感比較像？',opts:['你敢靠近我，但也看得懂我','我們一直互相反殺，看誰先死機','很自然，不需要一直說破','明確讓我知道你很想要我','我拒絕固定風格'],traits:{A:['confidence','trust'],B:['play','spark'],C:['tension','balance'],D:['reciprocity','spark'],E:['freedom','contrast']}}
]
};
const labels={
freedom:['THE FREE HEART','你需要靠近，但不需要被佔有。最舒服的關係，是兩個完整的人仍然保有自己的世界。'],clarity:['THE CLEAR SIGNAL','你不怕空間，你怕的是模糊。把話說清楚，反而能讓你給出更大的自由。'],spark:['THE LIVE WIRE','對你來說，好玩不是附加題。沒有好奇、笑聲與化學反應，再完美的條件也很難讓心真的上線。'],trust:['THE STEADY CHOICE','你真正要的安全感不是二十四小時報備，而是關鍵時刻知道：這個人不會跑。'],depth:['THE DEEP DIVER','你會被「還有東西沒看完」的人吸引。你想知道的不只是他做什麼，而是他為什麼成為現在的他。'],balance:['THE CO-PILOT','你傾向把愛看成共同工程：不是誰犧牲自己，而是兩個人一直找新的平衡點。'],boundary:['THE LINE KEEPER','你願意給機會，也願意談；但自由不是無限額。反覆踩線會讓你很快看清答案。'],competence:['THE QUIET RESPECT','吸引可以從外表開始，但真正讓你留下的往往是 respect：他有能力處理自己，也有能力面對問題。'],soft:['THE SOFT SPOT','你並不排斥依賴，你只是希望柔軟是選擇而不是負擔。被信任、被需要，對你其實很有殺傷力。'],contrast:['THE PLOT TWIST','你很吃反差。越不是一眼就能讀完的人，越容易讓你的注意力停久一點。'],direct:['THE STRAIGHT SHOT','你寧願知道真相，也不想耗在猜測。喜歡、困惑、界線——能講就講。'],aesthetic:['THE EYE CONTACT','承認吧，質感真的會讓你多看兩眼。但它通常只是入口，不是最後留下你的原因。'],tension:['THE SLOW BURN','你吃的是「我們都知道，但先不要講破」的張力。太快揭底牌，反而少了一點好玩。'],confidence:['THE GREEN LIGHT','你喜歡有自信的靠近，但前提是對方看得懂你的反應。主動可以，接管不行。'],reciprocity:['THE RETURN SERVE','你可以主動，但你需要球被打回來。對你而言，被想要本身就是 chemistry 的一部分。'],play:['THE MENACE','你很吃互相接梗與反殺。調情如果不能讓你笑，殺傷力會少一大截。'],attention:['THE TELL','真正打中你的常常不是大招，而是「原來你有在注意我」。'],exclusivity:['THE PRIVATE VERSION','你要的不是萬人迷，而是某些版本只有你看得到。'],sensory:['THE CRITICAL HIT','氣味、距離、聲音這些感官訊號，可能比你願意承認的更有殺傷力。']
};
const quotes={freedom:'「靠近我，但不要把我變成你的全部。」',clarity:'「你把話說清楚，我反而可以給你很大的空間。」',spark:'「跟你在一起要好玩，但別拿我的安全感開玩笑。」',trust:'「我不需要你一直在；我需要知道真的出事時你會在。」',depth:'「讓我想繼續認識你，比讓我第一眼驚艷更重要。」',balance:'「我們不用一樣，但要願意一起找答案。」',boundary:'「我會給機會，但不是無限次。」',competence:'「心動讓我靠近，尊敬才讓我留下。」',soft:'「你可以需要我，但別把自己的人生交給我負責。」',contrast:'「我喜歡那些不能五分鐘就看完的人。」',direct:'「有事就講。我可以處理真相，不想處理猜謎。」',aesthetic:'「好看會讓我多看一眼，有趣才會讓我留下。」',tension:'「最好玩的通常是還沒說破，但我們都知道。」',confidence:'「你可以很明確地靠近，但選擇權還是在我們兩個手上。」',reciprocity:'「我可以先走一步，但我也想看到你朝我走。」',play:'「讓我笑，然後在我沒防備的時候突然認真。」',attention:'「不是你做了多大的事，是你真的有看到我。」',exclusivity:'「我不需要你對世界冷淡，我只想知道我對你真的不同。」',sensory:'「理智在線。然後他靠近，而且很好聞。完。」'};
const $=s=>document.querySelector(s), screens=['landing','how','map','game','results'];
let save=loadSave();
let run=null;
function fresh(){return{version:2,completed:[],scores:{},chapterStats:{},chapterAnswers:{},lastChapter:'catch',updatedAt:Date.now()}}
function loadSave(){try{return {...fresh(),...JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}')}}catch{return fresh()}}
function persist(){save.updatedAt=Date.now();localStorage.setItem(STORAGE_KEY,JSON.stringify(save))}
function show(id){screens.forEach(x=>$('#'+x).classList.toggle('active',x===id));window.scrollTo({top:0,behavior:'smooth'})}
function overallKnown(extra=0){return Math.min(100,Math.round((save.completed.length/CHAPTERS.length)*100+extra/CHAPTERS.length))}
function initLanding(){if(save.completed.length||save.chapterStats.catch){$('#startBtn').innerHTML='繼續研究 <span>→</span>';$('#landingLede').innerHTML=`你回來了。<br>目前我大概懂你 <strong>${overallKnown()}%</strong>。別擔心，還有很多地方可以打臉我。`}else{$('#startBtn').innerHTML='開始實驗 <span>→</span>'}}
function renderMap(){const unlockedCount=save.completed.includes('catch')?2:1;$('#mapKnown').textContent=overallKnown()+'%';$('#mapWelcome').textContent=save.completed.length?`歡迎回來。你已經完成 ${save.completed.length} 個章節。下一層會更深，也更欠揍。`:'第一章先從最表面的心動開始。後面會越來越不客氣。';$('#chapterGrid').innerHTML=CHAPTERS.map((c,i)=>{const complete=save.completed.includes(c.key),unlocked=i<unlockedCount&&!c.locked,current=unlocked&&!complete;const stat=save.chapterStats[c.key];let stateTxt=complete?'COMPLETE':unlocked?'UNLOCKED':'LOCKED';return `<article class="chapter-card ${complete?'complete':current?'current':'locked'} ${unlocked?'unlocked':''}" data-chapter="${c.key}" data-unlocked="${unlocked}"><span class="chapter-state">${stateTxt}</span><span class="chapter-num">CHAPTER ${c.num} · ${c.subtitle.toUpperCase()}</span><h3>${c.title}</h3><p>${c.desc}</p>${stat?`<div class="chapter-score">CAUGHT ${stat.caught}/${stat.total} · ${stat.accuracy}% ACCURACY</div>`:''}</article>`}).join('');document.querySelectorAll('.chapter-card.unlocked').forEach(el=>el.onclick=()=>startChapter(el.dataset.chapter))}
function chapterMeta(key){return CHAPTERS.find(c=>c.key===key)}
function startChapter(key){if(!Q[key])return;save.lastChapter=key;persist();run={key,i:0,selected:null,prediction:null,caught:0,answers:[],localScores:{}};renderQuestion();show('game')}
function traitScores(){const merged={...save.scores};if(run)Object.entries(run.localScores).forEach(([k,v])=>merged[k]=(merged[k]||0)+v);return merged}
function predict(q){const keys=Object.keys(q.traits);const history=(save.chapterAnswers[run.key]||[]).length+run.answers.length;if(!history)return keys[1]||keys[0];const scores=traitScores();let best=keys[0],bestScore=-999;keys.forEach(k=>{const base=(q.traits[k]||[]).reduce((n,t)=>n+(scores[t]||0),0);const tiny=Math.random()*.45;if(base+tiny>bestScore){bestScore=base+tiny;best=k}});return best}
function renderQuestion(){const qs=Q[run.key],q=qs[run.i],meta=chapterMeta(run.key);run.selected=null;run.prediction=predict(q);$('#chapterLabel').textContent=`CHAPTER ${meta.num} · ${meta.title}`;$('#questionCount').textContent=`${String(run.i+1).padStart(2,'0')} / ${qs.length}`;$('#progressBar').style.width=`${run.i/qs.length*100}%`;const chapterExtra=((run.i/qs.length)*100);$('#learnPercent').textContent=overallKnown(chapterExtra)+'%';$('#questionKicker').textContent=`SCENARIO ${String(run.i+1).padStart(2,'0')}`;$('#questionText').textContent=q.text;$('#predictionText').textContent=run.prediction;$('#predictionHint').textContent=run.i<4?'先別急著證明我錯。':run.i<10?'嗯，我開始抓到你的套路了。':'現在開始真的有點危險。';$('#options').innerHTML=q.opts.map((o,i)=>{const k='ABCDE'[i];return `<button class="option" data-key="${k}"><span class="option-key">${k}</span><span class="option-text">${o}</span>${k===run.prediction?'<span class="predicted-badge">MY BET</span>':''}</button>`}).join('');$('#customWrap').hidden=true;$('#customAnswer').value='';$('#lockBtn').disabled=true;$('#questionCard').hidden=false;$('#predictionCard').hidden=false;$('#revealCard').hidden=true;document.querySelectorAll('.option').forEach(b=>b.onclick=()=>selectAnswer(b.dataset.key,b))}
function selectAnswer(k,b){run.selected=k;document.querySelectorAll('.option').forEach(x=>x.classList.toggle('selected',x===b));$('#customWrap').hidden=k!=='E';$('#lockBtn').disabled=false;if(k==='E')$('#customAnswer').focus()}
function lockAnswer(){if(!run.selected)return;const q=Q[run.key][run.i],hit=run.selected===run.prediction;run.caught+=hit?1:0;(q.traits[run.selected]||[]).forEach(t=>run.localScores[t]=(run.localScores[t]||0)+1);run.answers.push({q:run.i,a:run.selected,p:run.prediction,custom:run.selected==='E'?$('#customAnswer').value.trim():'',hit});$('#questionCard').hidden=true;$('#predictionCard').hidden=true;$('#revealCard').hidden=false;$('#revealCard').className='reveal-card '+(hit?'caught':'missed');$('#revealStamp').textContent=hit?'CAUGHT.':'MISSED.';$('#revealTitle').textContent=hit?(run.key==='flirt'?'……好，這題你真的很好抓。🙂':'Okay. 這題我抓到了。'):'好。研究模型需要更新。🙂';const top=topTraits(traitScores(),1)[0];const copies=hit?['先別得意，我只是暫時讀懂你一次。','可惡。你這個反應已經開始有規律了。','你以為你藏得很好。沒有。']:['你比第一眼難猜一點。很好。','這題打臉成功。研究員已記仇。','嗯？原來這條線比我以為的更強。'];$('#revealCopy').textContent=(hit?copies[run.i%copies.length]:copies[run.i%copies.length])+(top?` 目前「${labels[top][0]}」訊號最高。`:'');const chapterExtra=((run.i+1)/Q[run.key].length)*100;$('#revealPercent').textContent=overallKnown(chapterExtra)+'%';$('#learnPercent').textContent=overallKnown(chapterExtra)+'%'}
function nextQuestion(){run.i++;if(run.i>=Q[run.key].length)return finishChapter();renderQuestion()}
function topTraits(scores,n=4){return Object.entries(scores).sort((a,b)=>b[1]-a[1]).slice(0,n).map(x=>x[0])}
function finishChapter(){Object.entries(run.localScores).forEach(([k,v])=>save.scores[k]=(save.scores[k]||0)+v);save.chapterAnswers[run.key]=run.answers;save.chapterStats[run.key]={caught:run.caught,total:run.answers.length,accuracy:Math.round(run.caught/run.answers.length*100)};if(!save.completed.includes(run.key))save.completed.push(run.key);persist();renderResults();show('results')}
function renderResults(){const scores=traitScores(),tops=topTraits(scores,4),dom=tops[0]||'depth',meta=labels[dom],cm=chapterMeta(run.key);$('#reportLabel').textContent=`CATCH ME / ${cm.title} REPORT`;$('#caughtScore').textContent=run.caught;$('#resultDate').textContent=new Intl.DateTimeFormat('zh-TW',{year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());$('#resultSub').textContent=run.caught>=11?'討厭。你居然真的滿好猜的。但你的答案不是標籤，是一組會互相拉扯的需求。':run.caught>=7?'我抓到一些，但你成功打臉我很多次。很好，這才像真人。':'恭喜，你把預測模型弄得很難看。這份報告反而因此比較有意思。';$('#dominantName').textContent=meta[0];$('#dominantCopy').textContent=meta[1];$('#insightList').innerHTML=tops.slice(0,3).map((t,i)=>`<div class="insight"><strong>0${i+1} · ${labels[t][0]}</strong><span>${labels[t][1]}</span></div>`).join('');const max=Math.max(...tops.map(t=>scores[t]||0),1);$('#dimensionBars').innerHTML=tops.map(t=>`<div><div class="dim-meta"><span>${labels[t][0]}</span><span>${scores[t]||0}</span></div><div class="dim-track"><div class="dim-fill" style="width:${(scores[t]||0)/max*100}%"></div></div></div>`).join('');$('#resultQuote').textContent=quotes[dom]||'「別急著定義我。繼續學。」';$('#continueBtn').innerHTML=run.key==='catch'?'解鎖 FLIRT WITH ME <span>→</span>':'回到章節地圖 <span>→</span>'}
function goMap(){run=null;renderMap();initLanding();show('map')}
function shareResult(){const last=save.lastChapter,stat=save.chapterStats[last]||{caught:0,total:15};const dom=topTraits(save.scores,1)[0]||'depth';const txt=`CATCH ME｜${chapterMeta(last)?.title||'REPORT'}\nAI 抓到我 ${stat.caught}/${stat.total} 次。\n目前最強訊號：${labels[dom][0]}\n${quotes[dom]}\n\nDon't label me. Learn me.`;navigator.clipboard?.writeText(txt).then(toast).catch(toast)}
function toast(){$('#toast').classList.add('show');setTimeout(()=>$('#toast').classList.remove('show'),2200)}
function resetAll(){if(!confirm('真的要清除全部章節、答案和藍圖？這不能復原。'))return;localStorage.removeItem(STORAGE_KEY);save=fresh();run=null;initLanding();show('landing')}
$('#startBtn').onclick=()=>{renderMap();show('map')};$('#howBtn').onclick=()=>show('how');$('#howStartBtn').onclick=()=>{renderMap();show('map')};document.querySelectorAll('[data-back]').forEach(b=>b.onclick=()=>show(b.dataset.back));$('#mapHomeBtn').onclick=()=>{initLanding();show('landing')};$('#quitBtn').onclick=()=>{persist();renderMap();show('map')};$('#lockBtn').onclick=lockAnswer;$('#nextBtn').onclick=nextQuestion;$('#continueBtn').onclick=goMap;$('#shareBtn').onclick=shareResult;$('#resetBtn').onclick=resetAll;
initLanding();